### PR TITLE
[Major] Integrate inspectpack3 - faster, better, and more colorful!

### LINKED ISSUE #240: Webpack v4 plugin support
> Please provide a description of the bug / issue, and provide the details below:

I'm seeing these deprecation warnings when running webpack-dashboard in webpack v4 with `process.traceDeprecation = true;` in my webpack config:

```
$ node_modules/.bin/webpack-dev-server --config ./webpack.config.js
(node:16541) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
    at DashboardPlugin.apply (/Users/daniel/y/iui/node_modules/webpack-dashboard/plugin/index.js:98:14)
    at webpack (/Users/daniel/y/iui/node_modules/webpack/lib/webpack.js:37:12)
    at startDevServer (/Users/daniel/y/iui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:379:16)
    at processOptions (/Users/daniel/y/iui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:361:5)
    at Object.<anonymous> (/Users/daniel/y/iui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:504:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
(node:16541) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at DashboardPlugin.apply (/Users/daniel/y/iui/node_modules/webpack-dashboard/plugin/index.js:117:14)
    at webpack (/Users/daniel/y/iui/node_modules/webpack/lib/webpack.js:37:12)
    at startDevServer (/Users/daniel/y/iui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:379:16)
    at processOptions (/Users/daniel/y/iui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:361:5)
    at Object.<anonymous> (/Users/daniel/y/iui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:504:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```

I'm also seeing a lot of `Worker error Error: No code sections found` but I see that is being discussed in #234.

====================================================================

###### Steps to reproduce the problem

Add `new DashboardPlugin()` to plugins in webpack v4.

====================================================================

###### More Details

- What operating system are you on?
OS X 10.12
- What terminal application are you using?
iTerm 2
- What version of webpack-dashboard are you using?
1.1.1
- What is the output of running `echo $TERM`?
xterm-256color

### PR DESCRIPTION
**Pull request by ryan-roemer**
This is a major update to `webpack-dashboard` with breaking changes. And a lot of speed and coolness.

## Breaking changes

- Requires node6+.
- Use the webpack internal stats object instead of real bundles. This is faster and with less futzing / parsing on the dashboard's end. Should permanently fix the `no code sections` found errors.
- We've removed command flags / plugin options that no longer apply like `--root`, etc.

### Modules

- Removed `min` and `min+gz` estimated file sizes from modules outputs. This dramatically speeds up the dashboard and reduces CPU usage.

### Versions

- Version skews should be detected more accurately and much faster thanks to dramatically improved heuristics from `inspectpack`.

### Duplicates

- Duplicates now reports on duplicate files that are (1) completely identical, and (2) the same package name and file path but with different sources. The first are low hanging fruit for optimizations in your build -- you've literally got the same thing multiple times. The latter needs to be coalesced at the package dependency level -- something the versions output can help with.

## Issues

- Upgrade hooks to work in webpack1-4 with abstraction. Fixes #240

## Refactoring

- Switch from `chalk` to using Blessed's built-in tags for coloring. This is definitely the way to go as things like table spacing don't work with chalk strings and work like a charm with Blessed tags.
- Update dependencies and remove lots of unused things (like `lodash`, `chalk`, `bluebird` and a whole lot of `babel*` that apparently wasn't used anyways).
    - New `inspectpack` is way slimmer and faster, with no more binary dependencies!
- Switch to yarn-only workflow in dev.
- Bump Travis node versions.

screen shot 2018-05-23 at 4 01 39 pm

_Dev note_: Take a look at https://github.com/FormidableLabs/inspectpack/pull/63 for being able to test webpack-dashboard locally with any version of webpack and any inspectpack test fixture scenario!

### CODE REVIEW

File: dashboard/index.js [hunk 1]
```diff
@@ -26,16 +25,43 @@ const DEFAULT_SCROLL_OPTIONS = {
...
 
     this.color = options.color || "green";
     this.minimal = options.minimal || false;
-    this.setData = this.setData.bind(this);
-
     this.stats = null;
 
+    // Data binding, lookup tables.
+    this.setData = this.setData.bind(this);
+    this.actionForMessageType = {
```
Comment (ryan-roemer) [inline dashboard/index.js]: I moved this up to save us from continually re-creating and setting this object below.
